import numpy as np
from scipy.ndimage import gaussian_filter, distance_transform_edt


def tangential_diffusion_step(data, voxel_mm, dt, eps=1e-6):
    """
    One explicit step of pure TANGENTIAL diffusion: smooths only within
    the local tangent plane of the intensity surface (perpendicular to
    the gradient), leaving the along-gradient (normal) direction alone.

    This is the key difference from isotropic Gaussian blur: blurring
    across the gradient is what shrinks/rounds an isosurface (mean-
    curvature-flow-like behaviour - fast on high-curvature features like
    a nose tip, slow on flat regions). Diffusing ONLY tangentially
    smooths fine within-surface texture/noise while leaving the
    isosurface's position governed almost entirely by actual curvature -
    so low-curvature coarse shape (nose, chin) survives far more
    iterations than isotropic blur would allow, while high-curvature fine
    texture (skin detail, noise) is what actually gets removed.

    data:     current intensity volume (float)
    voxel_mm: (vx, vy, vz) physical voxel spacing, matching data's axis
              order, so gradients/Hessians are physically correct for
              anisotropic voxels
    dt:       explicit time step. Keep small for stability - see
              tangential_deface's default, which picks a conservative
              value automatically from voxel_mm.
    """
    vx, vy, vz = voxel_mm
    gx, gy, gz = np.gradient(data, vx, vy, vz)

    Ixx = np.gradient(gx, vx, axis=0)
    Iyy = np.gradient(gy, vy, axis=1)
    Izz = np.gradient(gz, vz, axis=2)
    Ixy = np.gradient(gx, vy, axis=1)
    Ixz = np.gradient(gx, vz, axis=2)
    Iyz = np.gradient(gy, vz, axis=2)

    grad_mag_sq = gx * gx + gy * gy + gz * gz

    # Second derivative along the LOCAL GRADIENT direction (n_hat^T H n_hat,
    # expressed without explicitly normalizing n_hat - dividing by
    # |grad|^2 instead of |grad| once at the end achieves the same thing
    # and avoids a redundant sqrt).
    I_nn = (gx * gx * Ixx + gy * gy * Iyy + gz * gz * Izz +
            2 * gx * gy * Ixy + 2 * gx * gz * Ixz + 2 * gy * gz * Iyz) / (grad_mag_sq + eps)

    laplacian = Ixx + Iyy + Izz
    tangential_laplacian = laplacian - I_nn

    return data + dt * tangential_laplacian


def build_tangential_pyramid(data, voxel_mm, n_levels, iters_per_level, dt, presmooth_sigma_mm=1.0):
    """
    Same 'mip-pyramid' pattern as the earlier Gaussian-blur version, but
    each level is generated by repeated TANGENTIAL diffusion steps
    instead of increasing Gaussian sigma. Level 0 is a light isotropic
    pre-smooth only (stabilizes gradient/Hessian estimation against
    voxel-level noise - the same role a "little blur to start with"
    plays before computing gradients) rather than the raw data, since
    unsmoothed data can give a very noisy gradient direction estimate
    that makes the tangential decomposition itself noisy.
    """
    sigma_voxels = [presmooth_sigma_mm / v for v in voxel_mm]
    current = gaussian_filter(data.astype(np.float32), sigma=sigma_voxels)
    levels = [current.copy()]
    for _ in range(1, n_levels):
        for _ in range(iters_per_level):
            current = tangential_diffusion_step(current, voxel_mm, dt)
        levels.append(current.copy())
    return np.stack(levels, axis=0)


def tangential_deface(data, brain_mask, voxel_mm=(1.0, 1.0, 1.0),
                       boundary_drop=0.70, darken_floor=0.12, darken_ramp_mm=60.0,
                       smooth_ramp_mm=40.0, max_iters=30, n_levels=5,
                       presmooth_sigma_mm=1.0):
    """
    Same distance-based control structure as deface_by_distance (sharp
    intensity step at the mask boundary, increasing effect with distance)
    but using tangential diffusion instead of isotropic Gaussian blur as
    the smoothing mechanism - intended to smooth fine identifying detail
    without rounding off coarse facial geometry (nose, chin) the way
    isotropic blur does.

    smooth_ramp_mm: distance over which smoothing strength ramps from 0
                    to max_iters iterations of tangential diffusion
    max_iters:      diffusion strength ceiling (in iterations) at/beyond
                    smooth_ramp_mm
    n_levels:       pyramid levels to blend between (more = smoother
                    strength transitions, more compute)
    """
    dist_mm = distance_transform_edt(~brain_mask, sampling=voxel_mm)

    iters_per_level = max(1, max_iters // (n_levels - 1))
    dt = 0.15 * min(voxel_mm) ** 2  # conservative explicit-scheme step size

    pyramid = build_tangential_pyramid(data, voxel_mm, n_levels, iters_per_level, dt,
                                        presmooth_sigma_mm=presmooth_sigma_mm)

    target_iters = max_iters * np.clip(dist_mm / smooth_ramp_mm, 0.0, 1.0)
    target_iters[brain_mask] = 0.0

    level_positions = np.arange(n_levels) * iters_per_level
    level_idx_f = np.interp(target_iters.ravel(), level_positions, np.arange(n_levels))
    level_idx_f = level_idx_f.reshape(target_iters.shape)
    lo = np.floor(level_idx_f).astype(int)
    hi = np.clip(lo + 1, 0, n_levels - 1)
    frac = (level_idx_f - lo).astype(np.float32)

    lo_vals = np.take_along_axis(pyramid, lo[None, ...], axis=0)[0]
    hi_vals = np.take_along_axis(pyramid, hi[None, ...], axis=0)[0]
    smoothed = lo_vals * (1.0 - frac) + hi_vals * frac

    extra_fade = boundary_drop - (boundary_drop - darken_floor) * np.clip(dist_mm / darken_ramp_mm, 0.0, 1.0)
    result = smoothed * extra_fade

    result[brain_mask] = data[brain_mask]
    return result


def simple_deface(data, brain_mask, voxel_mm=(1.0, 1.0, 1.0),
                   dark_pct=50.0, smoothing_radius_mm=8.0, feather_mm=2.0,
                   inside_region_mm=5.0, outside_region_mm=10.0,
                   presmooth_sigma_mm=1.0):
    """
    Simplified variant of tangential_deface:
      1. Darkening is ADAPTIVE, not a flat percentage of each voxel's own
         value: brain_intensity (95th percentile within inside_region_mm
         of the mask boundary, inside the mask) and skin_intensity (95th
         percentile within outside_region_mm of the boundary, outside
         the mask) are measured first, then the smoothed volume is scaled
         by dark_pct/100 * brain_intensity/skin_intensity and CLAMPED at
         dark_pct/100 * brain_intensity. A flat percentage multiplier
         only guarantees skin ends up at dark_pct%% of its OWN original
         brightness - naturally bright fat/skin can still end up brighter
         than brain tissue after treatment, which is exactly the "thick
         patches of skin/fat remain visible" failure mode this fixes. The
         rescale ties the result to BRAIN intensity instead, and the
         clamp gives a hard, not just statistical, ceiling - so raising
         the raymarching threshold above dark_pct/100*brain_intensity
         should make all treated skin disappear while brain stays intact.
      2. Smoothing is a FIXED strength (no distance-dependent ramp) -
         smoothing_radius_mm sets this directly as a physical radius,
         converted internally to an iteration count via the standard
         diffusion-length relationship radius ~= sqrt(2*dt*n_iters).
      3. Smoothing+darkening is computed over the WHOLE volume - no
         restricted/protected computation region. The original is
         restored via a smooth alpha-feather blend (weight 1 = original,
         0 = fully treated) that ramps over feather_mm starting at the
         mask boundary.

    dark_pct:            target %% of brain_intensity for the fully-
                        treated region (0-100)
    smoothing_radius_mm: physical radius of the tangential smoothing,
                        applied uniformly (computed over the whole volume)
    feather_mm:          distance (mm) over which the blend weight ramps
                        from 1 (original) to 0 (fully treated)
    inside_region_mm:   depth inside the mask boundary used to measure
                        brain_intensity (95th percentile)
    outside_region_mm:  distance outside the mask boundary used to
                        measure skin_intensity (95th percentile)
    presmooth_sigma_mm: light isotropic pre-smooth for stable gradient
                        estimation (same role as in tangential_deface)
    """
    dt = 0.15 * min(voxel_mm) ** 2
    n_iters = max(1, round(smoothing_radius_mm ** 2 / (2 * dt)))

    dist_out_mm = distance_transform_edt(~brain_mask, sampling=voxel_mm)  # 0 inside mask, distance outside
    dist_in_mm = distance_transform_edt(brain_mask, sampling=voxel_mm)   # depth inside mask, 0 outside

    inside_region = brain_mask & (dist_in_mm <= inside_region_mm)
    outside_region = (~brain_mask) & (dist_out_mm <= outside_region_mm)

    if not inside_region.any():
        raise ValueError(f"No voxels found within {inside_region_mm}mm inside "
                          f"the mask boundary - inside_region_mm may be too "
                          f"small relative to the mask, or the mask is empty.")
    if not outside_region.any():
        raise ValueError(f"No voxels found within {outside_region_mm}mm "
                          f"outside the mask boundary - check the mask and "
                          f"outside_region_mm.")

    brain_intensity = np.percentile(data[inside_region], 95)
    skin_intensity = np.percentile(data[outside_region], 95)
    if skin_intensity <= 0:
        raise ValueError(f"skin_intensity measured as {skin_intensity} (<=0) - "
                          f"cannot compute a meaningful brain/skin ratio.")

    darken_factor = (dark_pct / 100.0) * (brain_intensity / skin_intensity)
    clamp_value = (dark_pct / 100.0) * brain_intensity

    # Smoothing + darkening computed over the WHOLE volume, uniformly -
    # no masking during computation at all. The mask only comes in below,
    # to decide how much of this treated result to blend in.
    sigma_voxels = [presmooth_sigma_mm / v for v in voxel_mm]
    current = gaussian_filter(data.astype(np.float32), sigma=sigma_voxels)
    for _ in range(n_iters):
        current = tangential_diffusion_step(current, voxel_mm, dt)
    treated = np.minimum(current * darken_factor, clamp_value)

    weight = 1.0 - np.clip(dist_out_mm / feather_mm, 0.0, 1.0)  # 1 inside mask, ramps to 0 over feather_mm
    weight[brain_mask] = 1.0  # exact inside the mask (dist=0 already gives this, explicit for clarity)

    return weight * data + (1.0 - weight) * treated


def _cli():
    import argparse
    import nibabel as nib

    parser = argparse.ArgumentParser(
        description="Simplified deface: adaptive darkening (based on the "
                     "measured brain/skin intensity ratio, with a hard "
                     "clamp) and fixed-strength tangential smoothing "
                     "applied over the whole volume, with the original "
                     "restored via a smooth feathered blend near the "
                     "brain mask boundary."
    )
    parser.add_argument("brain", help="Path to the brain/head NIfTI image")
    parser.add_argument("mask", help="Path to the brain mask NIfTI image")
    parser.add_argument("output", help="Path to write the defaced NIfTI image")
    parser.add_argument("--dark_pct", type=float, default=50.0,
                         help="Target %% of measured brain_intensity for "
                              "the fully-treated region (0-100). Default 50.")
    parser.add_argument("--smoothing_radius_mm", type=float, default=8.0,
                         help="Physical radius (mm) of tangential "
                              "smoothing, applied uniformly over the "
                              "whole volume. Default 8.")
    parser.add_argument("--feather_mm", type=float, default=2.0,
                         help="Distance (mm) over which the original-vs- "
                              "treated blend weight ramps, starting at "
                              "the mask boundary. Default 2.")
    parser.add_argument("--inside_region_mm", type=float, default=5.0,
                         help="Depth (mm) inside the mask boundary used "
                              "to measure brain_intensity. Default 5.")
    parser.add_argument("--outside_region_mm", type=float, default=10.0,
                         help="Distance (mm) outside the mask boundary "
                              "used to measure skin_intensity. Default 10.")
    args = parser.parse_args()

    img = nib.load(args.brain)
    mask_img = nib.load(args.mask)
    data = np.asanyarray(img.dataobj)
    mask = np.asanyarray(mask_img.dataobj)
    if mask.shape != data.shape:
        raise ValueError(f"Mask shape {mask.shape} does not match brain "
                          f"image shape {data.shape}")
    mask = mask > 0.5

    voxel_mm = [float(v) for v in img.header.get_zooms()[:3]]

    dt = 0.15 * min(voxel_mm) ** 2
    n_iters = max(1, round(args.smoothing_radius_mm ** 2 / (2 * dt)))

    # Measure and print brain/skin intensities up front - lets you sanity
    # check the ratio (and the resulting darken_factor/clamp_value) before
    # waiting for the smoothing pass to finish.
    dist_out_mm = distance_transform_edt(~mask, sampling=voxel_mm)
    dist_in_mm = distance_transform_edt(mask, sampling=voxel_mm)
    inside_region = mask & (dist_in_mm <= args.inside_region_mm)
    outside_region = (~mask) & (dist_out_mm <= args.outside_region_mm)
    brain_intensity_50 = np.percentile(data[inside_region], 50)
    brain_intensity = np.percentile(data[inside_region], 90)
    skin_intensity = np.percentile(data[outside_region], 90)
    darken_factor = (args.dark_pct / 100.0) * (brain_intensity / skin_intensity)
    clamp_value = (args.dark_pct / 100.0) * brain_intensity_50

    print(f"brain_intensity (p95, {args.inside_region_mm}mm inside)  = {brain_intensity:.2f}")
    print(f"skin_intensity  (p95, {args.outside_region_mm}mm outside) = {skin_intensity:.2f}")
    print(f"darken_factor = {darken_factor:.4f}   clamp_value = {clamp_value:.2f}")
    print(f"smoothing_radius_mm={args.smoothing_radius_mm:.1f} (n_iters={n_iters}, dt={dt:.4f})  "
          f"feather_mm={args.feather_mm:.1f}")

    out = simple_deface(data, mask, voxel_mm=voxel_mm,
                         dark_pct=args.dark_pct,
                         smoothing_radius_mm=args.smoothing_radius_mm,
                         feather_mm=args.feather_mm,
                         inside_region_mm=args.inside_region_mm,
                         outside_region_mm=args.outside_region_mm)

    out_img = nib.Nifti1Image(out.astype(np.float32), img.affine, img.header)
    nib.save(out_img, args.output)
    print(f"Wrote defaced volume to {args.output}")


if __name__ == "__main__":
    _cli()
